### ISSUE TITLE
Enable Draggable but Disable Droppable

### ISSUE THREAD

**Issue by icangku** [ParadeTo/vue-tree-list#10]
What i want to achieve is, i only want to have one children from parent, but the children is draggable, but they cannot have children again, because maximum children tree is one, how to do to this?

thank you

**Comment by ParadeTo** [comment]
you can fork this repository and modify as you want

**Comment by Mr-arvin** [comment]
great idea, i want to achieve modify name and delete catalog, i will try to achieve that!

**Comment by inversator** [comment]
Hey.
I'm trying to track the dragging of an item inside a single parent node, but I don’t find such an event.

This is needed to track the reordering of elements within the parent.
How can this be done?
