### ISSUE TITLE
"Document is not defined" on component registration

### ISSUE THREAD

**Issue by Atakspor** [ParadeTo/vue-tree-list#105]
I try to use `vue-tree-list` with local registration but when I put `VueTreeList` in `components`, I get the following error:

I am just following the given example and just copy-pasting it. Has anyone else encountered this? I am using `Nuxt`. 

Edit: This actually happens whenever I import and use something from `vue-tree-list`. `Tree` also causes this.

![image](https://user-images.githubusercontent.com/9057785/112991546-edaf0600-916f-11eb-8508-940ffe3f52b6.png)

**Comment by twocngdagz** [comment]
@Atakspor 


How did you resolved this?
