### ISSUE TITLE
引用后会报“[Vue warn]: Failed to mount component: template or render function not defined.”

### ISSUE THREAD

**Issue by varyoung** [ParadeTo/vue-tree-list#2]
引用方式：
import {VueTreeList,Tree, TreeNode} from './tree/index'
export default {
  name: 'HelloWorld',
  render: (createElement) => createElement(createElement),
  components: {
      VueTreeList:VueTreeList
  },
  data () {
    return {
        newTree: {},
        data: new Tree([
          {
            name: 'Node 1',
            id: 1,
            pid: 0,
            children: [
              {
                name: 'Node 1-2',
                id: 2,
                isLeaf: true,
                pid: 1
              }
            ]
          },
          {
            name: 'Node 2',
            id: 3,
            pid: 0
          },
          {
            name: 'Node 3',
            id: 4,
            pid: 0
          }
        ])
    }
  }
}

tree下的文件
index.js
Tree.js
VueTreeList.vue

**Comment by ParadeTo** [comment]
这个错误应该是针对你自己的组件吧

**Comment by varyoung** [comment]
不是的，这个是新用的demo项目，是按照你的指引去使用的。直接使用是不行的，经过修改是可以用的，十分感谢你优秀的组件

**Comment by ParadeTo** [comment]
奇怪了，我试了是可以的
