### ISSUE TITLE
"Сhange-name" is triggered every time a character is entered

### ISSUE THREAD

**Issue by inversator** [ParadeTo/vue-tree-list#30]
Hello.
Change-name is triggered every time a character is entered.
Is this correct?
Is it possible to trigger a focus change event?

**Comment by sontungx305** [comment]
I have the same issues, I'm using ajax to update the name to the database when onChangeName trigger, it makes a lot of requests.

**Comment by ParadeTo** [comment]
@sontungx305 Actually, I don't think it is a bug. You must have used `input`, `keyup`, `keydown` event of `<input></input>` tag, right? The events is triggered every time when you type. You can write a `debounce` function to resolve your problem.

**Comment by fbasar** [comment]
Please use vue-tree-list2 is a lot problem fixed

**Comment by tristan-tsl** [comment]
maybe you are right, but i think good package should not use the event to condition, hope you can package it in event method

**Comment by tristan-tsl** [comment]
hi, can you publish it to npmjs? thank you

**Comment by tristan-tsl** [comment]
when you was use it,, just write condition code in old logic:

                if ('blur' != params["eventType"]) return;

**Comment by ParadeTo** [comment]
Have published! Sorry for late.

**Comment by adrianoGaspar** [comment]
Hello, I don't know if I missed something, but apparently when I type I have the node but when the onblur event is fired I lose the node, so I can't compare the original value with the old one to decide whether or not to change the API
