### ISSUE TITLE
Change Icons

### ISSUE THREAD

**Issue by 0815joe** [ParadeTo/vue-tree-list#33]
Hi!
Is there a chance to change the node icons?

**Comment by ParadeTo** [comment]
you can use `slot`, pls refer to the doc

**Comment by elotmanik** [comment]
Hi!
Is there a way to specify an icon by file type (pdf, doc...=)
Thank you

**Comment by ParadeTo** [comment]
> Hi!
> Is there a way to specify an icon by file type (pdf, doc...=)
> Thank you
Use `slot`

**Comment by ParadeTo** [comment]
> Hi!
> Is there a way to specify an icon by file type (pdf, doc...=)
> Thank you

`Slot` may satisfy you.

**Comment by farshid3003** [comment]
I want to set different icons for different nodes. slots does not do it.

**Comment by ramanangru** [comment]
I just updated the code, with below javascript code and wrote custom class & changed the icon for the leaf and folder.

     ```
    this.treeInpObj = new Tree(this.filesArray);
     setTimeout(function(){
          let leafNode = document.getElementsByClassName('vtl-icon-file');
          for(let i=0;i<leafNode.length;i++){
            leafNode[i].parentNode.className="leafNode";
          }

          let folderNode = document.getElementsByClassName('vtl-icon-folder');
          for(let i=0;i<folderNode.length;i++){
            folderNode[i].parentNode.className="folderNode";
          }
        },100)
```
