### ISSUE TITLE
How do you use @drop,@drop-up events among events?

### ISSUE THREAD

**Issue by FactAttacker** [ParadeTo/vue-tree-list#34]
hello 
this is good library!

but I don't know how to use it @drop, @drop-up events 
can you make a case if you don't mind?
I don't understand

**Comment by ParadeTo** [comment]
```
****1****
****2****
```

Suppose there are 2 divs as show above, when you drag 2 into 1, drop event will fire, when you drag 2 to the up of 1, the drop-up event will fire.

**Comment by FactAttacker** [comment]
yes. 
I see what you mean.
But as you say, the event didn't start
What I'm asking is not a condition of occurrence. It's an example code.

`
                            <VueTreeList 
                                v-if="sortTreeList.length !== 0"
                                :model="sortTreeList" 
                                :default-expanded="false"
                                @drop="NodeDrop"
                            />
`
NodeDrop was not executed.

Thank you so much for answering my article

**Comment by Bexazak** [comment]
@ParadeTo 
events `@drop` and `@drop-up` - do not work. They do not react at all.
can show an example of use?
for example, `@click` works fine.
Thank you very much.

**Comment by ParadeTo** [comment]
Sorry for not update the version. Please use the latest version 1.3.2.
By the way, the event is change to @drop-after and @drop-before
