### ISSUE TITLE
Can it be made into a tree table?

### ISSUE THREAD

**Issue by Nicolas-shanpao** [ParadeTo/vue-tree-list#35]
![image](https://user-images.githubusercontent.com/28480091/58466427-3f4d6a80-816c-11e9-8642-1b3e1bc583a5.png)
Just like this,I can show other information

**Comment by ParadeTo** [comment]
> ![image](https://user-images.githubusercontent.com/28480091/58466427-3f4d6a80-816c-11e9-8642-1b3e1bc583a5.png)
> Just like this,I can show other information

you can use element-ui
