### ISSUE TITLE
return Tree without prototypes

### ISSUE THREAD

**Issue by sjsiegel001** [ParadeTo/vue-tree-list#44]
I want to send the Tree object over an endpoint to persist it in the database. Short of getting the innerHTML of the `<pre>{{newTree}}</pre>` element, is there a way to get a simple json representation of vm.$data.newTree after getNewTree() without the prototypes that can be saved in a database?

I've tried JSON.parse(JSON.stringify(vm.newTree)) but this converts all the primitives to strings

**Comment by ParadeTo** [comment]
Have you resolved?

**Comment by sjsiegel001** [comment]
JSON.parse(JSON.stringify(vm.newTree)) was working fine, it turned out to be an issue with my server side code. Thank you though!
