### ISSUE TITLE
Data as JSON

### ISSUE THREAD

**Issue by AntennaMM** [ParadeTo/vue-tree-list#5]
im having trouble as where i need to upload the modified tree data to the database. but now cant as they are not in json format. please help.

**Comment by ParadeTo** [comment]
you can walk the result recursively like demo.

**Comment by AntennaMM** [comment]
the getTreeChange function in the demo is it?

**Comment by ParadeTo** [comment]
`getNewTree: function () {
        const vm = this
        function _dfs (oldNode) {
          let newNode = {}

          newNode.name = oldNode.name
          newNode.pid = oldNode.pid
          newNode.isLeaf = oldNode.isLeaf
          newNode.id = oldNode.id

          if (oldNode.children && oldNode.children.length > 0) {
            newNode.children = []
            for (let i = 0, len = oldNode.children.length; i < len; i++) {
              newNode.children.push(_dfs(oldNode.children[i]))
            }
          }
          return newNode
        }

        vm.newTree = _dfs(vm.data)
      }
    }`
