### ISSUE TITLE
lost css styles on 1.3.2+ version

### ISSUE THREAD

**Issue by christiancazu** [ParadeTo/vue-tree-list#55]
just work css on 1.3.0 version

**Comment by ParadeTo** [comment]
You need to link css file which is `dist/vue-tree-list.css` by yourself. We will update our doc later.

**Comment by beyoursun** [comment]
it need to include css in the lib i see, otherwise it will be a breaking change.

**Comment by ParadeTo** [comment]
Yes, according to our version plan, it must be compatible with old version. Please fix it, thanks. @beyoursun
