### ISSUE TITLE
How I can add more field for each node to edit?

### ISSUE THREAD

**Issue by vedmant** [ParadeTo/vue-tree-list#58]
How I can add more field for each node to edit?
For example I have menu list each menu has name, url and few other checkboxes and selectors.
I wanted to find a solution, similar to what Wordpress has for their menu, when you can see tree view, can expand individual item and edit different fields there: https://easywpguide.com/wp-content/uploads/2019/12/menu.jpg

**Comment by ParadeTo** [comment]
Sorry. It does't support this feature yet.

**Comment by vedmant** [comment]
If someone interested I was able to implement this using https://www.antdv.com/components/tree/ with nodes scopedSlots.
