### ISSUE TITLE
HTML5 dragleave fired when hovering a child element

### ISSUE THREAD

**Issue by ko22009** [ParadeTo/vue-tree-list#59]
https://stackoverflow.com/questions/7110353/html5-dragleave-fired-when-hovering-a-child-element

**Comment by ko22009** [comment]
And also change outline to border, bcz you have troubles with correctly get size of element.

**Comment by ParadeTo** [comment]
It is correct for this component that `dragleave` fired when hovering a child element.

**Comment by ParadeTo** [comment]
> And also change outline to border, bcz you have troubles with correctly get size of element.

You mean change the hovering style? When do you want to get the size of element?

**Comment by ko22009** [comment]
Maybe, this problem doesn't happen. When I move to child element, I doesn't see outline border active.
