### ISSUE TITLE
Adding new actions to node item

### ISSUE THREAD

**Issue by atxy2k** [ParadeTo/vue-tree-list#67]
Hi, someone knows how to add new actions to node items? ... for example, I have 3 main nodes:

- Node 1
- Node 2
- Node 3 

But I have to add to node 2 an item from database, then, I want to have in the node 2 row a button, and when user press it, open a modal, add to database and add the result as child of node 2. Another action I want to do is a custom edition, for example, in node 2, I want to have a custom edit button, and when user press it, open a modal and edit the node with all attributes (4 or 5), and later, saved it and manually, update the tree.

**Comment by ParadeTo** [comment]
Cannot support your request right now. You can fork it and modify as you want. Sorry.
