### ISSUE TITLE
Adding click handler for nodes and children

### ISSUE THREAD

**Issue by abhilashdharam1** [ParadeTo/vue-tree-list#7]
Hey @ParadeTo , can you please add this functionality such that we can catch this event from parent (by exposing some event). Tried with $emit but doesn't work with child and leaf nodes. Your help is highly appreciated. Thank you.

**Comment by DesDevCharan** [comment]
@ParadeTo , Facing the same issue. Tried modifying the plugin with event bus for child nodes as well. Struggling with this over the weekend.

**Comment by ParadeTo** [comment]
c846f7a9c10fb443371fbe9d1bdcf38a7a995278
