### ISSUE TITLE
Issue with Webpack?

### ISSUE THREAD

**Issue by liquidvisual** [ParadeTo/vue-tree-list#8]
Hey there, great library! I'm trying to figure out how to integrate this into my Vue Webpack environment but I'm getting an error which I'm not sure how to solve :/

    Error in data(): "TypeError: __WEBPACK_IMPORTED_MODULE_1_vue_tree_list__.VueTreeList.Tree is not a constructor"

Any ideas or help would be appreciated!

**Comment by ParadeTo** [comment]
How you use it?

**Comment by liquidvisual** [comment]
Thanks for responding so quickly!

I'm using single file components with the .vue extension and my setup looks like this:

```
<template>...</template>
<script>
    import { VueTreeList, Tree, TreeNode } from 'vue-tree-list';

    var treeData = new VueTreeList.Tree([
        {
            name: 'Node 1',
            id: 1,
            pid: 0,
            dragDisabled: true,
        }
    ]);
</script>
```

```
AppFileSystem.vue?954f:67 Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0_vue_tree_list__.VueTreeList.Tree is not a constructor
```

It looks like the error is related to the class function, I'm not sure what to do.

**Comment by ParadeTo** [comment]
Sorry, the `readme` is wrong.

This is the right way:
```
    var treeData = new Tree([
        {
            name: 'Node 1',
            id: 1,
            pid: 0,
            dragDisabled: true,
        }
    ]);
```

**Comment by liquidvisual** [comment]
That worked, thanks for that!
