### ISSUE TITLE
Feature request: Change title of operation icons

### ISSUE THREAD

**Issue by severila** [ParadeTo/vue-tree-list#84]
Instead of hard-coding `add tree node` https://github.com/ParadeTo/vue-tree-list/blob/66bc19baaafdfb75275e2f84813ba2f3767ae2f3/src/VueTreeList.vue#L61 it would be nice if we could customize the text of the title.
Same for the other titles.

**Comment by HombreGeek** [comment]
How can I Change the titles if I make and npm to install in a vue project? 
Thanks in advance..
